const CANVASWIDTH = 2000;
const CANVASHEIGHT = 800;

const SPRITEHEIGHT = 100;
const SPRITEWIDTH = 100;

const SPRITEPIXELHEIGHT = 10;
const SPRITEPIXELWIDTH = 10;

var DEBUGBOOL = true;

// Render globals. They allow to quickly change the positions of each game element

const RESET_POS_X = CANVASWIDTH-SPRITEWIDTH*2;
const RESET_POS_Y = CANVASHEIGHT-SPRITEHEIGHT;

const END_TURN_POS_X = CANVASWIDTH-SPRITEWIDTH;
const END_TURN_POS_Y = CANVASHEIGHT-SPRITEHEIGHT;

